# Generated by Django 4.2.1 on 2023-05-18 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='endereco',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='idade',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='telefone',
            new_name='phone',
        ),
    ]
