# Generated by Django 4.2.1 on 2023-05-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_endereco_pessoa_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Person',
        ),
    ]
